#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

if [[ $(git status --porcelain) ]]; then
  git add composer.json
  git commit -m 'Automated commit'
  git push
fi
